### ISSUE TITLE
Latest commit should be tagged as release version

### ISSUE THREAD

**Issue by firyalff** [z0mt3c/node-restify-validation#78]
Since the docs already covering array and object schema validation, i think commits after latest release (v1.1.1) should be released too. A little bit frustating while you're doing exactly what's in the docs, but array and object validation doesn't work.

**Comment by gurtagel** [comment]
YESSSSSSSS!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by andrewzey** [comment]
Hey, I'll be taking over development and maintenance of this package. I just published the next version*: https://github.com/z0mt3c/node-restify-validation/releases/tag/v1.3.0

* not sure why `npm version minor` bumped to `1.3.0` instead of `1.2.0`, probably related to the tags that broke the convention of prefixing with `v`. Won't be a problem going forward.
